remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Let's Create a Safer Marshall
description: Marshall avenue between Victoria Street and Lexington Parkway desparately needs traffic calming and pedestrian safety measures implemented
